### ISSUE TITLE
Incompatibility with other plugins and <Enter> maps

### ISSUE THREAD

**Issue by Townk** [Townk/vim-autoclose#25]
I just receive this bug report by email and I don't want to loose track of it:

---

> Whenever I use an auto-complete feature (the built-in VIM one or omnicppcomplete) an annoying effect appears: if the auto-complete popup is visible and I press <enter> to select the current option, the current option is inserted after the cursor (as should be), but, unfortunately, a carriage return is also inserted (as shouldn't be).
> 
> I have the following details:
> If I disable autoclose, the carriage return is not inserted.
> If I comment out the line inoremap <buffer> <silent> <CR>      <C-R>=<SID>Enter()<CR> in CreateExtraMaps, the carriage return is not inserted, but this, of course, disables the really nice indentation of a {} block that you have implemented. At the moment, I am forced to live with this option as the <cr> insertion is much more distracting.
> My understanding is that this behavior is a result of a misinteraction between autocomplete and supertab because without supertab, the default behavior for vim is to insert the carriage return after hitting enter. However, supertab adds the nice functionality of just completing the selection on <enter> and I would like to keep that if possible.

---

**Comment by artm** [comment]
Ah, I see. I'll have to look into that, the Enter / Space expansion is still a bit experimental.

**Comment by artm** [comment]
do I get it right, to see this problem I need just our plugin + supertab?

**Comment by Townk** [comment]
I think so, but I honestly didn't had time to test it myself

**Comment by glanotte** [comment]
I am experiencing a conflict between the two. checking out head on both breaks the end behavior in ruby. I was able to isolate it to the most recent commit for your repo, and the conflict was with vim-endwise. I did catch some weirdness with supertab as well, but it was less defined.

If I create a new file foo.rb and type `def foo<cr>`, no end is created.

if I checkout the `b63af10761e5b783aecd189847c73ca3202bb5fd` commit, the behavior is fixed.

I hope this helps.

**Comment by sanchopansa** [comment]
@artm Hi -- I was the person to originally report the issue, so I thought I would clarify, since github seems to have stripped portions of my email posted above by Townk.
1. You only need supertab and autoclose to reproduce this.
2. Open a file for editing in vim, enter insert mode and use the built-in vim autocompletion c-x c-p. Supertab allows you to use tab to cycle through the available options. Hit Enter on one of the options: the option is inserted after the cursor, but also a newline is inserted.
3. Remove autoclose and repeat the steps in 2. The text is inserted and this time no new line is inserted.

Thanks for looking into this and let me know if you cannot reproduce it and/or if you need additional details.

**Comment by thenoseman** [comment]
@glanotte:
workaround in your `.vimrc`: `let g:AutoCloseExpandEnterOn = ""`

**Comment by glanotte** [comment]
@thenoseman:

Thanks, it worked like a charm

**Comment by installero** [comment]
@thenoseman:

Thanx! That worked for me too!

**Comment by Townk** [comment]
As far as I could check here this problem happens because of the popup menu being shown. We do have an option on AutoClose that lets you define a special behavior for certain keys when the popup menu is visible.

Using this allow you to tell AutoClose to issue a "<C-Y>" when <Enter> is pressed and the popup menu is visible. This most likely will fix the "Compatibility" problem with SuperTab.

Here is what I use on my own .vimrc:

let g:AutoClosePumvisible = {"Esc": "<C-E>", "Enter": "<C-Y>"}

I'll add these maps as the default behavior so no one has to worry about this in the future.

**Comment by alexbel** [comment]
It seems to me that supertab capability problem still appears.
I've tried clean vim installation on openSUSE and on ubuntu with latest versions of supertab and autoclose.
When you hit ESC on element in popup menu, this element actually will not appear. The text would be the same as you typed and vim would be in 'insert' mode instead of 'normal' mode.
